<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UserSecretsId>f1aeb4f0-5835-420a-97e5-3c67ea47410d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\1.jpg" />
    <None Remove="images\2.jpg" />
    <None Remove="images\3.jpg" />
    <None Remove="images\4.jpg" />
    <None Remove="images\5481541a-60c6-4699-ac0d-12a968525faa.jpg" />
    <None Remove="images\About1.jpg" />
    <None Remove="images\avatar2.png" />
    <None Remove="images\B0001.jpg" />
    <None Remove="images\B0002.jpg" />
    <None Remove="images\B0003.jpg" />
    <None Remove="images\banner1.png" />
    <None Remove="images\bird.gif" />
    <None Remove="images\blog1.gif" />
    <None Remove="images\blog10.gif" />
    <None Remove="images\C0001.jpg" />
    <None Remove="images\C0002.jpg" />
    <None Remove="images\C0003.jpg" />
    <None Remove="images\C0004.jpg" />
    <None Remove="images\C0005.jpg" />
    <None Remove="images\C0006.jpg" />
    <None Remove="images\C0007.jpg" />
    <None Remove="images\C0008.jpg" />
    <None Remove="images\C0009.jpg" />
    <None Remove="images\CAM0001.jpg" />
    <None Remove="images\CAM0002.jpg" />
    <None Remove="images\CAM0003.jpg" />
    <None Remove="images\CAM0004.jpg" />
    <None Remove="images\Logo.png" />
    <None Remove="images\placeholder.png" />
    <None Remove="images\test2.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DUPSS.APIClients\DUPSS.ApiClients.csproj" />
    <ProjectReference Include="..\DUPSS.API\DUPSS.API.csproj" />
    <ProjectReference Include="..\DUPSS.Common\DUPSS.Common.csproj" />
    <ProjectReference Include="..\DUPSS.DTO\DUPSS.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\1.jpg" />
    <Resource Include="images\2.jpg" />
    <Resource Include="images\3.jpg" />
    <Resource Include="images\4.jpg" />
    <Resource Include="images\5481541a-60c6-4699-ac0d-12a968525faa.jpg" />
    <Resource Include="images\About1.jpg" />
    <Resource Include="images\avatar2.png" />
    <Resource Include="images\B0001.jpg" />
    <Resource Include="images\B0002.jpg" />
    <Resource Include="images\B0003.jpg" />
    <Resource Include="images\banner1.png" />
    <Resource Include="images\bird.gif" />
    <Resource Include="images\blog1.gif" />
    <Resource Include="images\blog10.gif" />
    <Resource Include="images\C0001.jpg" />
    <Resource Include="images\C0002.jpg" />
    <Resource Include="images\C0003.jpg" />
    <Resource Include="images\C0004.jpg" />
    <Resource Include="images\C0005.jpg" />
    <Resource Include="images\C0006.jpg" />
    <Resource Include="images\C0007.jpg" />
    <Resource Include="images\C0008.jpg" />
    <Resource Include="images\C0009.jpg" />
    <Resource Include="images\CAM0001.jpg" />
    <Resource Include="images\CAM0002.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\CAM0003.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\CAM0004.jpg" />
    <Resource Include="images\Logo.png" />
    <Resource Include="images\placeholder.png" />
    <Resource Include="images\test2.gif" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
